### ISSUE TITLE
ePUB-Export funktioniert nicht (mehr?)

### ISSUE THREAD

**Issue by chrisreuter** [chrisreuter/dazhandbuch#3]
Auf http://dazhandbuch.de/ führt Klick auf Icon Drucken/das komplette Buch/als ePUB speichern zu folgender Fehlermeldung:

Liegt das am AEWB-Server?

**Comment by web2write** [comment]
Ich kann den Fehler komischerweise mit Fehlermeldung auf dem Mac nur in Safari und Chrome reproduzieren, sowie unter Windows mit Edge.
Firefox ruft zwar die Seite
http://dazhandbuch.de/export/epub
auf - es passiert aber nichts - auch keine Fehlermeldung.
Der Fehlercode "5002 ist leider nicht sehr aussagekräftig, deutet aber auf einen "internen Serverfehler" hin
http://www.checkupdown.com/status/E500_de.html
 - das könnte durchaus mit Rechten, Einstellungen etc. auf dem AEWB-Server zu tun haben.

**Comment by chrisreuter** [comment]
Ok, danke!

Am 30. April 2016 um 18:55 schrieb web2write <notifications@github.com>:

**Comment by Claudissima** [comment]
Hallo, Chris, ich probiere einfach mal aus, was ich hier so machen kann, hoffe das ist ok ;-)

**Comment by chrisreuter** [comment]
Hallo Claudia, ja, bitte, dafür sind wir ja hier auf github. Du scheinst dich ja schon ganz gut zurecht zu finden. Dein 2. Kommentar ist im passenden Diskussionspfad. ;-)

**Comment by Claudissima** [comment]
:)



Mit besten Grüßen

Claudia Lühmann 

(von meinem Xperia gesendet)

---- Christian Reuter schrieb ----

**Comment by chrisreuter** [comment]
Nachtrag vom Mai 2016. Fehler tritt nicht auf eigenem Server auf.
=> Ursache ist die Konfiguration des AEWB-Servers
